project:
  type: website
  output-dir: docs
website:
  title: "Chi Zhang"
  navbar:
    right:
      - text: "About"
        href: index.html
      - cv.qmd
      - projects.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/andreaczhang
      - icon: twitter
        href: https://twitter.com/Andreasheenn
format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

