project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "你好，欢迎来到陈晨的个人网站"
  site-url: https://github.com/ChenChenGith
  favicon: misc/info/favicon.jpg
  repo-url: https://github.com/ChenChenGith/ChenChenGith.github.io
  repo-actions: [edit, issue]

  page-footer:
    left: |
      模板来自[chizapoth](https://github.com/chizapoth/chizapoth.github.io)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      # - text: "Projects"
      #   href: projects/projects.qmd
      
      - text: "教学/Teaching"
        href: teaching/teaching.qmd
        
      - text: "项目/Projects"
        href: projects/projects.qmd

      - text: "中文简历/CV"
        href: about_me.qmd


format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细


