project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hello, I'm Chi"
  site-url: https://andreaczhang.github.io
  favicon: misc/info/favicon.png
  repo-url: https://github.com/andreaczhang/andreaczhang.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2023, Chi Zhang"
    right: 
      - icon: github
        href: https://github.com/andreaczhang/andreaczhang.github.io
      - icon: twitter
        href: https://twitter.com/Andreasheenn

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Projects"
        href: projects/projects.qmd
      
      - text: "Teaching"
        href: teaching/teaching.qmd
        
      - text: "R packages"
        href: rpkg/rpkg.qmd
           
      - text: "Talks"
        href: talks/talks.qmd

      - text: "Blog/notes"
        href: blog/blog.qmd
        
      - text: "About"
        menu: 
          - text: "About me"
            href: about_me.qmd
          - text: "CV"
            href: misc/info/CV_Chi_Zhang.pdf


format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: "Atkinson Hyperlegible"


